### ISSUE TITLE
Инициализация при создании

### ISSUE THREAD

**Issue by copych** [GyverLibs/mString#10]
Алекс, я не очень силен в программировании, вопрос такой: можно ли расширить конструктор, чтоб был вариант с инициализацией, типа такого:
```
mString<50> str = "vasya";
```
вместо 
```
mString<50> str;
str = "vasya";
```
Или, может, уже сейчас можно инициализировать при создании (просто, я не знаю как))) так не выходит:
```
mString<50> str {"vasya"};
```
???

**Comment by GyverLibs** [comment]
Да, нужно добавить конструкторов. Не помню почему пришлось отказаться от этой затеи, где то был конфликт. Попробую
