### ISSUE TITLE
Поддерживает ли кириллицу?

### ISSUE THREAD

**Issue by Stass48** [GyverLibs/mString#11]
Приветствую! Собственно, вопрос в заголовке. Спасибо.

**Comment by GyverLibs** [comment]
привет, на том же уровне что и обычная String

**Comment by Stass48** [comment]
😥
Мне нужно парсить текст. Но у меня банальная проблема, я не могу посчитать количество символов в строке. Кириллица занимает два байта, вместо одного. Еще интереснее, если кириллица перемешана с латиницей. Вообще не ясно как с этой кашей работать.

**Comment by GyverLibs** [comment]
Вот тут https://alexgyver.ru/arduino-algorithms/ глава СТРОКИ

**Comment by GyverLibs** [comment]
Если будет время на досуге, займусь

**Comment by Stass48** [comment]
Все же наберусь наглости и попрошу... Можно ли как-то получить символ по индексу? Я бы дальше может быть сам бы справился. Не понимаю как работает ваш код по подсчету символов (

**Comment by Stass48** [comment]
Хотя бы подскажите в какую сторону думать

**Comment by GyverLibs** [comment]
Проблема в том, что русский символ - это несколько байт. Нужно сначала определить, что это кириллица, а потом переписать её куда нибудь. Либо в char массив длиной 4 байта (2-3 байта + 0) - это будет строка из одной буквы. Либо в тип wchar_t, тут уже надо подтягивать теорию как это всё кодируется и работает

**Comment by Stass48** [comment]
Спасибо!
Кстати, заметил, что для ваших библиотек отсутствует кнопка удаления в Arduino IDE, не плохо бы пофиксить. В частности это библиотека таймера и стрингов, другие не смотрел.

**Comment by Stass48** [comment]
Я вот это имел ввиду:

![image](https://github.com/GyverLibs/mString/assets/143362590/367e40d8-45d2-4778-8044-2e77a58798a8)

**Comment by GyverLibs** [comment]
Это что за ide такая?

**Comment by Stass48** [comment]
Arduino IDE 2.2.1

**Comment by GyverLibs** [comment]
не работал в ней, очень сырая и глючная

**Comment by GyverLibs** [comment]
> Какую лучше использовать?

Для мелочёвки - IDE 1.x. Для крупных проектов - VS code + platformio. Придётся немного пострадать, но это того стоит

**Comment by Stass48** [comment]
Спасибо за подсказку. В том и дело, что я совсем не могу разобраться в этом PlatformIO. У меня не заработало там то, что заработало здесь. Плюс вот эта менюшка выпадающая с параметрами, можно настроить ключевые параметры работы микроконтроллера. Там я даже не знаю, где это все искать. Для меня, как для новичка, это все очень сложно. Но разбираться толком некогда. На меня кинули довольно тяжелый проект, нужно делать. Но надо сказать, за это время я дофига чего нового узнал.

**Comment by GyverLibs** [comment]
Всё верно: страдать, гуглить, изучать кривую документацию на английском и молиться, что оно не перестанет работать после каких то изменений))

**Comment by GyverLibs** [comment]
Либо использовать VS code как редактор, а заливать через arduino ide. Но тут ещё прикол, что platformio в разы быстрее компилирует код, для есп32 это прям в десятки раз, что разница колоссальная

**Comment by Stass48** [comment]
Я как раз так и использовал, вскод и расширение платформио. Код действительно компилируется быстрее, но когда не понимаешь, как это работает, очень тяжело сориентироваться :(

**Comment by GyverLibs** [comment]
Понять и не получится. Нужно открывать документацию и читать какие конфиги есть к выбранной плате

**Comment by Stass48** [comment]
В будущем займусь)

Пока я мучаю искусственный интеллект. Представьте, таки домучил, ору :D

[вот](https://chat.openai.com/share/eb0e7d98-efc8-46d2-8ea9-6c8c19a9b009)

**Comment by Stass48** [comment]
Посмотрите на этот код, он работает. Хотелось бы знать ваше мнение.
Там только на входе функции нужно подправить вместо char* • const char*
