### ISSUE TITLE
error: 'uint32_t' was not declared in this scope

### ISSUE THREAD

**Issue by 1g0rrr** [GyverLibs/mString#4]
Какая-то странная ошибка сразу после установки и инклуда по инструкции

![image](https://user-images.githubusercontent.com/51457/185952416-c1a215a6-ae3d-4e2b-a248-c1a41bba182d.png)

**Comment by GyverLibs** [comment]
Где компилится?

**Comment by GyverLibs** [comment]
> Компилирую с помощью VSCode

В этом и был вопрос) а если добавить 
`#include <Arduino.h>` в файл utils.cpp, ошибка пропадет?
