### ISSUE TITLE
Не получается распарсить с минусом

### ISSUE THREAD

**Issue by Inoy-LL** [GyverLibs/mString#5]
jsonSend = "[1234,-2345,3456,-1]";
   int data[4];
   jsonSend.remove(0,1);
   byte get=jsonSend.parseInts(data,4,',',']');
     for (int i = 0; i < get; i++) {
    Serial.println(data[i]);   // 1234 -27655 3456 -29
  }

**Comment by GyverLibs** [comment]
Исправил в v1.3
