### ISSUE TITLE
Конкатенация с uint32_t не работает

### ISSUE THREAD

**Issue by MIMBOL228** [GyverLibs/mString#6]
### При работе с библиотекой обнаружилась проблема: конкатенация с uint32_t не работает. 
# Минимальный код:

Дополнительные данные:
- Версия библиотеки: 1.1.1
- МК: Mega328p (Arduino Uno)
- Версия Arduino IDE: 2.1.0
- Корректно ли работают ли встроенные примеры, в которых используются функции и конструкции, приводящие к багу в вашем коде: Да
- Какой код загружался, какая работа от него ожидалась и как он работает в реальности:
- - Код: ниже 
- - Ожидаемый текст: Time is 1685363781
- - Реальный текст: Time is 40005

```cpp
mString<30> text;
text = "Time is ";
uint32_t time = 1685363781;
text += time; 
```

# Код для удобных тестов:
```cpp
#include "mString.h"

void setup() {
  Serial.begin(9600);

  Serial.print("test: ");
  mString<30> text;
  text ;
  uint32_t time = 1685363781;
  text += time;
  Serial.println(text.buf); // test: Time is 40005

  Serial.print("test2: ");
  mString<30> text2;
  text2 = "Time is ";
  text2 += String(time);
  Serial.println(text2.buf); // test2: Time is 1685363781
}

void loop() {}

```

**Comment by GyverLibs** [comment]
спасибо, проблему нашёл, сейчас пофикшу

**Comment by GyverLibs** [comment]
Раз уж добрался до либы, добавлю оптимизации и пару новых приколов, к вечеру релизну
