### ISSUE TITLE
length() method returns Zero if use with external buffer

### ISSUE THREAD

**Issue by ShaggyDog18** [GyverLibs/mString#7]
Using the library with an external buffer requires to actualize the _len of the buffer because it is equal to zero at initialization. That's the reason lenght() method returns 0 as the buffer length even though it may content data.
To resolve the issue I would suggest adding method that would update _len and should be called before other library methods if use  the external buffer:
```
uint16_t updateBufLength(void){
	_len = strlen( buf );
	return _len;
}
```

**Comment by GyverLibs** [comment]
yep, thanks!

**Comment by GyverLibs** [comment]
wait, now I have clear in constructor
```cpp
    mString(char* nbuf, uint16_t size) {
        buf = nbuf;
        _MS_SIZE = size;
        clear();
    }
```
it is better idea because buffer can be uninitialised. Maybe I should make something like `mString(char* nbuf, uint16_t size, bool clear = true)` in constructor 🙄

**Comment by ShaggyDog18** [comment]
look, clearing (zeroing buf length) in constructor would not help. I am filling in the external buffer by reading to it from Serial with a regular assignment; then use your library for the buffer with data. So, each time I call a method from your library, internal _len is not actual because buf was changed/assigned a value "outside" as `buffer[i++] = Serial.read();`  That's why I need to update _len before calling any method, especially these that check up the _len before, like for example indexOf()...

**Comment by GyverLibs** [comment]
ah, ok
