### ISSUE TITLE
Compilation error on Platformio

### ISSUE THREAD

**Issue by sigmashig** [GyverLibs/mString#8]
Использую актуальную версию PlatformIo + Arduino Framework + ESP32. При компиляции файла в котором стоит использование внешнего буфера выдается ошибка в строке  `if (clear) clear();`
expression preceding parentheses of apparent call must have (pointer-to-) function type
{
	"resource": "/c:/Project/SigmaUtils/.pio/libdeps/esp-wrover-kit/mString/src/mString.h",
	"owner": "cpp",
	"severity": 8,
	"message": "'clear' cannot be used as a function",
	"startLineNumber": 53,
	"startColumn": 26,
	"endLineNumber": 53,
	"endColumn": 26
}

[ошибка](https://i.imgur.com/tNHWJKt.png)

Версия gcc, которая используется в этом фреймворке не разрешает использовать одноименные переменную и функцию.

**Comment by GyverLibs** [comment]
спасибо, пофиксил
